# Generated by Django 4.2.30 on 2026-07-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mes', models.IntegerField()),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sub_totales_activos', models.IntegerField()),
                ('sub_mensuales_nuevas_max', models.IntegerField()),
                ('sub_mensuales_perdidas_max', models.IntegerField()),
                ('tasa_perdida_base', models.DecimalField(decimal_places=4, default=0.02, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_perdida_nuevos_no_suscritos', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tasa_perdida_antiguos_suscritos', models.DecimalField(decimal_places=6, max_digits=15)),
                ('f_adquisicion', models.DecimalField(decimal_places=4, max_digits=15)),
                ('f_churn', models.DecimalField(decimal_places=4, max_digits=15)),
                ('usuarios_estables', models.IntegerField()),
                ('ingresos_totales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_optimo_1derivada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ganancia_maxima_2derivada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion', to='roseApp.mes')),
            ],
        ),
    ]
